replicaCount: 2

auth:
  adminPassword: admin
  adminUsername: admin

persistence:
  enabled: false

image:
  repository: marklogic-centos/marklogic-server-centos
  tag: 10-internal
  
tls:
  enabled: true
  secretNames: 
    - "marklogic-0-tls"
    - "ml-marklogic-0-self"
# resources: 
#   requests:
#     memory: "2800Mi"
#     cpu: "1000m"
#   limits:
#     memory: "2800Mi"
#     cpu: "1000m"

startupProbe:
  enabled: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false
