{{- if .Values.ingress.enabled -}}
{{- $haproxyServiceName := include "marklogic.haproxy.servicename" . -}}
{{- $svcPort := .Values.haproxy.frontendPort -}}
{{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
{{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "marklogic.ingress" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.selectorLabels" . | nindent 4 }}
  {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}  
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.haproxy.defaultAppServers.appservices.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $haproxyServiceName }}
                port:
                  number: {{ $svcPort }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.haproxy.defaultAppServers.admin.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $haproxyServiceName }}
                port:
                  number: {{ $svcPort }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.haproxy.defaultAppServers.manage.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $haproxyServiceName }}
                port:
                  number: {{ $svcPort }}
    - host: {{ .Values.ingress.additionalHost | quote }}
      {{- range $_, $v := .Values.haproxy.additionalAppServers }}
      {{ $path := printf "%v" (default $v.path)}}
      http:
        paths:
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $haproxyServiceName }}
                port:
                  number: {{ $svcPort }}
      {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end }}