{{- $adminPassword := (default (randAlphaNum 10) .Values.auth.adminPassword) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "marklogic.fullname" .))) }}
{{- if $secret }}
{{- $adminPassword = index $secret.data "password" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marklogic.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
type: Opaque
data:
    password: {{ $adminPassword }}
    username: {{ .Values.auth.adminUsername | b64enc | quote }}
    wallet-password: {{ .Values.auth.walletPassword | b64enc | quote }}

