{{- if not .Values.auth.secretName -}}
{{- $adminUsername := (default (printf "admin-%s" (randAlphaNum 5)) .Values.auth.adminUsername) | b64enc | quote }}
{{- $adminPassword := (default (randAlphaNum 10) .Values.auth.adminPassword) | b64enc | quote }}
{{- $walletPassword := (default (randAlphaNum 10) .Values.auth.adminPassword) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "marklogic.fullname" .))) }}
{{- if $secret }}
{{- $adminUsername = index $secret.data "username" }}
{{- $adminPassword = index $secret.data "password" }}
{{- $walletPassword = index $secret.data "wallet-password" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marklogic.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
type: Opaque
data:
    password: {{ $adminPassword }}
    username: {{ $adminUsername }}
    wallet-password: {{ $walletPassword }}
{{- end }}
