apiVersion: v1
kind: Service
metadata:
  name: {{ include "marklogic.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "marklogic.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: health-check
      port: 7997
    - protocol: TCP
      name: query-console
      port: 8000
    - protocol: TCP
      name: admin
      port: 8001
    - protocol: TCP
      name: manage
      port: 8002
