apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "marklogic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "marklogic.headlessServiceName" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "marklogic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "marklogic.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "marklogic.serviceAccountName" . }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8}}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      containers:
        - name: marklogic-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          volumeMounts:
            - name: datadir
              mountPath: /var/opt/MarkLogic
            {{- if .Values.additionalVolumeMounts }}
              {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
            {{- end }}
            - name: mladmin-secrets
              mountPath: /run/secrets/ml-secrets
              readOnly: true
          env:
            - name: MARKLOGIC_ADMIN_USERNAME_FILE
              value: "ml-secrets/username"
            - name: MARKLOGIC_ADMIN_PASSWORD_FILE
              value: "ml-secrets/password"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                    fieldPath: metadata.name
            - name: INSTALL_CONVERTERS
              value: {{ .Values.enableConverters | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "marklogic.fullname" . }}
          ports:
            - name: health-check
              containerPort: 7997
              protocol: TCP
            - name: xdqp-port1
              containerPort: 7998
              protocol: TCP
            - name: xdqp-port2
              containerPort: 7999              
              protocol: TCP
            - name: app-services
              containerPort: 8000
              protocol: TCP
            - name: admin
              containerPort: 8001
              protocol: TCP
            - name: manage
              containerPort: 8002
              protocol: TCP
            {{- if .Values.additionalContainerPorts }}
              {{- toYaml .Values.additionalContainerPorts | nindent 12 }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - '-c'
                  - |
                    MARKLOGIC_ADMIN_USERNAME="$(< /run/secrets/ml-secrets/username)"
                    MARKLOGIC_ADMIN_PASSWORD="$(< /run/secrets/ml-secrets/password)"

                    log () {
                      local TIMESTAMP=$(date +"%Y-%m-%d %T.%3N")
                      # Check to make sure pod doesn't terminate if PID value is empty for any reason
                      # If PID value is empty preStart hook logs are not recorded
                      if [ -n "$pid" ]; then
                          echo "${TIMESTAMP} $@" > /proc/$pid/fd/1
                      fi
                    }

                    pid=$(pgrep start.marklogic)
                    log "Info: [prestop] Prestop Hook Execution"

                    my_host=$(hostname -f)

                    log "Info: [prestop] MarkLogic Pod Hostname: "$my_host

                    for ((i = 0; i < 5; i = i + 1)); do
                        res_code=$(curl --anyauth --user $MARKLOGIC_ADMIN_USERNAME:$MARKLOGIC_ADMIN_PASSWORD \
                            -o /dev/null -m 10 -s -w %{http_code} \
                            -i -X POST --data "state=shutdown&failover=true" \
                            -H "Content-type: application/x-www-form-urlencoded" \
                            http://localhost:8002/manage/v2/hosts/$my_host?format=json)

                        if [[ ${res_code} -eq 202 ]]; then
                            log "Info: [prestop] Host shut down response code: "$res_code

                            while (true)
                            do
                              ml_status=$(service MarkLogic status)
                              log "Info: [prestop] MarkLogic Status: "$ml_status
                              if [[ "$ml_status" =~ "running" ]]; then
                                  sleep 5s
                                  continue
                              else
                                  break
                              fi
                            done
                            break
                        else
                            log "ERROR: [prestop] Retry Attempt: "$i
                            log "ERROR: [prestop] Host shut down expected response code 202, got "$res_code
                            sleep 10s
                        fi
                    done
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: health-check
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: health-check
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.logCollection.enabled }}
        - name: fluent-bit
          image: {{ .Values.logCollection.image }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: datadir
              mountPath: /var/opt/MarkLogic
            {{- if .Values.additionalVolumeMounts }}
              {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
            {{- end }}
            - name: {{ include "marklogic.fullname" . }}-fb-config-map
              mountPath: /fluent-bit/etc/
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources: {{- toYaml .Values.logCollection.resources | nindent 12 }}
        {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      dnsConfig:
        searches:
          - {{ include "marklogic.headlessURL" . }}
      volumes:
        - name: mladmin-secrets
          secret:
            secretName: {{ include "marklogic.authSecretNameToMount" . }}
        {{- if .Values.logCollection.enabled }}
        - name: {{ include "marklogic.fullname" . }}-fb-config-map
          configMap:
            name: {{ include "marklogic.fullname" . }}-fb-config-map
        {{- end }}
        {{- if not .Values.persistence.enabled }}
        - name: datadir
          emptyDir: {}
        {{- end }}
        {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
        {{- end }}
  {{- if or .Values.persistence.enabled .Values.additionalVolumeClaimTemplates }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels: 
          {{- include "marklogic.selectorLabels" . | nindent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote}}
          {{- end }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end}}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    {{- if .Values.additionalVolumeClaimTemplates }}
    {{- toYaml .Values.additionalVolumeClaimTemplates | nindent 4 }}
    {{- end }}
  {{- end }}
