apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "marklogic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
spec:
  serviceName: ml-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "marklogic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "marklogic.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "marklogic.serviceAccountName" . }}
      containers:
        - name: marklogic
          image: {{ .Values.image.repository}}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          volumeMounts:
            - name: ml-pvc
              mountPath: /var/opt/MarkLogic
          env:
            - name: ML_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: ml-secret
                  key: username
            - name: ML_ADMIN_PASS
              valueFrom:
                  secretKeyRef:
                    name: ml-secret
                    key: password
          envFrom:
            - configMapRef:
                name: marklogic-config
          command:
            - bash
            - '-c'
            - |
              echo '### Begin ML Container Config ###'

              # Set Hostname to the value of hostname command to /etc/marklogic.conf
              echo "export MARKLOGIC_HOSTNAME=$(hostname)" | sudo tee /etc/marklogic.conf

              cd ~

              AUTH_CURL="curl --anyauth --user $ML_ADMIN_USER:$ML_ADMIN_PASS -m 20 -s "

              # Start MarkLogic
              sudo service MarkLogic start
              sleep 5s

              # Initialize and Setup Admin User
              echo '### Initialize and Setup Admin User ###'
              ML_STATUS_CODE=`curl -s -o /dev/null --write-out %{response_code}  http://localhost:8001/admin/v1/init`
              if [ "$ML_STATUS_CODE" == "401" ]; then
                echo "Server is already configured." 
              else
                curl -X POST -d "" http://$HOSTNAME:8001/admin/v1/init
                sleep 5s

                curl -X POST -H "Content-type: application/x-www-form-urlencoded" \
                    --data "admin-username=$ML_ADMIN_USER" --data "admin-password=$ML_ADMIN_PASS" \
                    --data "realm=public" \
                    http://$HOSTNAME:8001/admin/v1/instance-admin
                sleep 10s

                # Turn on XDQP encryption via CMA
                $AUTH_CURL -X POST -H 'Content-Type: application/json' \
                    -d '{"config":[{"op":"update","group":[{"group-name":"Default","xdqp-ssl-enabled":true}]}]}' \
                    http://$HOSTNAME:8002/manage/v3/

                # Join Cluster
                if [ "$HOSTNAME" != "$ML_BOOTSTRAP_HOST" ]; then
                  echo "### joining cluster ###"
                  joiner=$HOSTNAME
                  cluster="$ML_BOOTSTRAP_HOST"
                  $AUTH_CURL -o host.xml -X GET -H "Accept: application/xml" http://${joiner}:8001/admin/v1/server-config
                  $AUTH_CURL -X POST -d "group=Default" --data-urlencode "server-config@./host.xml" -H "Content-type: application/x-www-form-urlencoded" -o cluster.zip http://${cluster}:8001/admin/v1/cluster-config

                  sleep 10s

                  $AUTH_CURL -X POST -H "Content-type: application/zip" --data-binary @./cluster.zip http://${joiner}:8001/admin/v1/cluster-config 
                  sleep 5s

                  rm -f host.xml
                  rm -f cluster.zip
                fi

              fi

              # mark the pod ready for readiness probe
              sudo touch /var/opt/MarkLogic/ready

              echo '### END ML Container Config ###'

              tail -f $MARKLOGIC_DATA_DIR/Logs/ErrorLog.txt
          ports:
            - containerPort: 7997
              name: health-check
            - containerPort: 7998
              name: cluster-port
            - containerPort: 7999
              name: cluster-port2
            - containerPort: 8000
              name: app-services
            - containerPort: 8001
              name: admin
            - containerPort: 8002
              name: manage
            - containerPort: 8003
              name: app
          livenessProbe:
            httpGet:
              path: /
              port: 7997
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 7997
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - ls
                - /var/opt/MarkLogic/ready
            initialDelaySeconds: 10
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 30
          resources:
            requests:
              memory: "3000Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
      dnsConfig:
        searches:
          - ml-headless.marklogic.svc.cluster.local
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: ml-pvc
        annotations:
          volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size}}