apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ml-marklogic-0-self
spec:
  # Secret names are always required.
  secretName: ml-marklogic-0-self
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - ML
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  commonName: "ml-marklogic-0.ml-marklogic-headless.default.svc.cluster.local"
  issuerRef:
    name: selfsigned-issuer
    
    kind: ClusterIssuer
    group: cert-manager.io